name: Deploy to Hostinger

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy Website to Hostinger
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📁 Sync files via FTP to Hostinger
        uses: SamKirsch/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./
          server-dir: ./public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
            **/.vscode/**
